version: '3.8'

networks:
  default:
    external: true
    name: "rfidNetwork"

services:
  mysql:
    image: mysql:latest
    container_name: rfid-local
    ports:
      - "3306:3306"
    environment:
      'MYSQL_ROOT_PASSWORD' : "asdf"
    restart: unless-stopped